old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.message_producer' service to send data.
        message:
            connection:       default
            exchange_options: { name: 'message', type: direct }

    consumers:
        message:
            connection:       default
            exchange_options: { name: 'message', type: direct }
            queue_options:    { name: 'message', arguments: {'x-dead-letter-exchange': ['S', 'message_dl']}}
            callback:         App\Consumer\MessageConsumer

        message_dl:
            connection:       default
            exchange_options: { name: 'message_dl', type: direct }
            queue_options:    { name: 'message_dl' }
            callback:         App\Consumer\MessageConsumer
